name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: npm install

    - name: Run a one-line script
      run: echo Hello, world! ${{ secrets.API_KEY }}

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.